### ISSUE TITLE
Command latency increases

### ISSUE THREAD

**Issue by akamaus** [dkolmakov/hm#13] opened 2019-10-12 15:21 UTC
After enabling hm in `.bashrc` shell started to feel somewhat sluggish. I even hear a sync-like activity of my HDD after entering each command. Maybe this strict transactional semantics is not needed really? Probably hm should return before data are synced to disk. Easy solution seem to just fork on each command and have parent to return immediately. More correct one is probably to start some daemon process to collect commands in RAM before committing DB transaction.

**Comment by dkolmakov** [comment] 2019-10-13 18:10
Is latency increased when an empty string is executed? I was able to reproduce the issue, but it looks like the latency is increased only when a command different from the previous one is executed.

**Comment by dkolmakov** [comment] 2019-10-14 16:16
@akamaus, can you please check the branch "fix-latency"? I have implemented some kind of workaround for the issue. Now all commands are stored in the temporary text file and are loaded to the database when `hm` interface function is called. It solves the latency issue on my machine.

**Comment by dkolmakov** [comment] 2019-10-22 18:10
@akamaus I have merged all changes to master, so please check it.

**Comment by dkolmakov** [comment] 2020-01-17 16:37
Looks like there is no problem with latency anymore :)

**Closed by dkolmakov** 2020-01-17 16:37 UTC
Labels: bug, enhancement
